name = "weeding"
main = "worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[vars]
NVIDIA_API_KEY = "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"
